name: Publish Docker Image

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image (IMAP + Delivery Service)
        run: |
          IMAGE_NAME=ghcr.io/lsflk/raven
          VERSION=${GITHUB_REF_NAME}
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$VERSION .

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/lsflk/raven
          VERSION=${GITHUB_REF_NAME}
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$VERSION